#include <stdint.h>

/*
 * A12 MESSAGE_PACING: one-variable diagnostic derivative of tested A11.
 *
 * A11 already solved the frequent Condor input/FFB death by guarding the
 * physical SideWinder RESET (C5 01) for 75 ms after the UART becomes idle.
 *
 * Remaining observations with A11:
 *   - repeated Condor launches became much more reliable;
 *   - sometimes Condor has live axes but no physical FFB at all;
 *   - after a good Condor session the centering spring can remain resident;
 *   - ForceTest itself can produce all physical FFB effects correctly.
 *
 * A12 changes ONLY the physical FIFO drain policy again:
 *   - preserve the A11 75 ms RESET guard;
 *   - treat each queued SideWinder command as one logical MIDI message;
 *   - after every NON-RESET logical message has fully left UART0, wait
 *     1,000 us before starting the next logical message;
 *   - after RESET C5 01, wait 75,000 us instead of 1,000 us.
 *
 * The waits are ASYNCHRONOUS: this function simply returns until the timer
 * expires. TinyUSB, USB HID input reports, main loop and joystick polling are
 * not intentionally delayed.
 *
 * Recognized messages generated by the current PicoWinder/A10 engine:
 *   C5 xx                        2 bytes  device control
 *   B5 xx id                    3 bytes  start/stop/free operation
 *   B5 xx id A5 lo hi           6 bytes  modify
 *   F0 ... F7                   SysEx    effect DEFINE
 *
 * No descriptor, effect translation, allocator, PIO, input, gain or effect
 * semantics are changed in A12.
 */

#define QBASE       ((volatile uint8_t*)0x20010000u)
#define QMASK       0x0fffu
#define QDATA_OFF   8u

/* Same reserved diagnostic RAM area used successfully by A11. */
#define PSTATE_ADDR 0x20012f00u
#define P_MAGIC     0xA1201ACEu

#define UART0_DR     (*(volatile uint32_t*)0x40034000u)
#define UART0_FR     (*(volatile uint32_t*)0x40034018u)
#define UART_FR_BUSY 0x08u
#define UART_FR_TXFF 0x20u
#define UART_FR_TXFE 0x80u

#define TIMERAWL       (*(volatile uint32_t*)0x40054028u)
#define NORMAL_GAP_US  1000u
#define RESET_GUARD_US 75000u
#define MAX_SYSEX_SCAN 256u

struct PacingState {
    uint32_t magic;
    uint32_t phase;
    uint32_t deadline;
    uint16_t remaining;
    uint16_t message_len;
    uint32_t post_gap_us;
};
#define PS ((volatile struct PacingState*)PSTATE_ADDR)

enum {
    PH_IDLE = 0u,
    PH_SENDING = 1u,
    PH_WAIT_UART_EMPTY = 2u,
    PH_WAIT_GAP = 3u
};

static inline uint16_t q_head(void) { return *(volatile uint16_t*)(QBASE+0u); }
static inline uint16_t q_tail(void) { return *(volatile uint16_t*)(QBASE+2u); }
static inline void q_set_tail(uint16_t v) { *(volatile uint16_t*)(QBASE+2u)=v; }
static inline uint8_t q_byte(uint16_t p) { return QBASE[QDATA_OFF + (p & QMASK)]; }
static inline uint16_t q_next(uint16_t p) { return (uint16_t)((p+1u)&QMASK); }
static inline uint16_t q_occupancy(uint16_t head,uint16_t tail) {
    return (uint16_t)((head-tail)&QMASK);
}
static inline uint8_t q_at(uint16_t tail,uint16_t offset) {
    return q_byte((uint16_t)((tail+offset)&QMASK));
}

static inline void init_state(void) {
    if (PS->magic != P_MAGIC || PS->phase > PH_WAIT_GAP) {
        PS->phase=PH_IDLE;
        PS->deadline=0u;
        PS->remaining=0u;
        PS->message_len=0u;
        PS->post_gap_us=NORMAL_GAP_US;
        PS->magic=P_MAGIC;
    }
}

/* Return 0 until one COMPLETE logical message is present in the FIFO. */
static uint16_t message_length(uint16_t tail,uint16_t head,uint32_t *post_gap) {
    uint16_t occ=q_occupancy(head,tail);
    if (occ==0u) return 0u;

    uint8_t b0=q_at(tail,0u);

    if (b0==0xc5u) {
        if (occ<2u) return 0u;
        uint8_t cmd=q_at(tail,1u);
        *post_gap=(cmd==0x01u)?RESET_GUARD_US:NORMAL_GAP_US;
        return 2u;
    }

    if (b0==0xb5u) {
        if (occ<3u) return 0u;
        /* Current engine writes MODIFY atomically as B5 xx id A5 lo hi. */
        if (occ>=4u && q_at(tail,3u)==0xa5u) {
            if (occ<6u) return 0u;
            *post_gap=NORMAL_GAP_US;
            return 6u;
        }
        *post_gap=NORMAL_GAP_US;
        return 3u;
    }

    if (b0==0xf0u) {
        uint16_t limit=occ;
        if (limit>MAX_SYSEX_SCAN) limit=MAX_SYSEX_SCAN;
        for (uint16_t i=1u;i<limit;i++) {
            if (q_at(tail,i)==0xf7u) {
                *post_gap=NORMAL_GAP_US;
                return (uint16_t)(i+1u);
            }
        }
        /* DEFINE packets used here are far below 256 bytes. If 256 bytes are
           present without F7, do not guess a boundary or corrupt framing. */
        return 0u;
    }

    /* Defensive recovery only. All current producers start messages with
       C5, B5 or F0. If framing is ever lost, transmit one byte as a standalone
       unit rather than deadlocking the complete FIFO forever. */
    *post_gap=NORMAL_GAP_US;
    return 1u;
}

__attribute__((used,noinline))
void a12_paced_drain(void) {
    init_state();

    if (PS->phase==PH_WAIT_UART_EMPTY) {
        uint32_t fr=UART0_FR;
        if ((fr & (UART_FR_TXFE|UART_FR_BUSY)) != UART_FR_TXFE) return;
        PS->deadline=TIMERAWL + PS->post_gap_us;
        PS->phase=PH_WAIT_GAP;
        return;
    }

    if (PS->phase==PH_WAIT_GAP) {
        uint32_t now=TIMERAWL;
        if ((int32_t)(now-PS->deadline) < 0) return;
        PS->phase=PH_IDLE;
    }

    uint16_t tail=q_tail();
    uint16_t head=q_head();

    if (PS->phase==PH_IDLE) {
        uint32_t gap=NORMAL_GAP_US;
        uint16_t len=message_length(tail,head,&gap);
        if (len==0u) return;
        PS->remaining=len;
        PS->message_len=len;
        PS->post_gap_us=gap;
        PS->phase=PH_SENDING;
    }

    /* Keep A10/A11's conservative per-call raw-byte ceiling. We may return
       earlier when UART FIFO is full; message framing state survives. */
    uint32_t budget=15u;
    tail=q_tail();
    head=q_head();

    while (PS->phase==PH_SENDING && PS->remaining!=0u && budget!=0u) {
        if (tail==head) return; /* qwrite is atomic; defensive only */
        if (UART0_FR & UART_FR_TXFF) return;

        UART0_DR=(uint32_t)q_byte(tail);
        tail=q_next(tail);
        q_set_tail(tail);
        PS->remaining--;
        --budget;

        if (PS->remaining==0u) {
            PS->phase=PH_WAIT_UART_EMPTY;
            return;
        }
    }
}
