#ifndef USB_REPORT_IDS_H
#define USB_REPORT_IDS_H
#define REPORT_ID_INPUT_JOYSTICK 1
#define REPORT_ID_OUTPUT_SET_EFFECT 2
#define REPORT_ID_OUTPUT_SET_ENVELOPE 3
#define REPORT_ID_OUTPUT_SET_CONDITION 4
#define REPORT_ID_OUTPUT_SET_PERIODIC 5
#define REPORT_ID_OUTPUT_SET_CONSTANT 6
#define REPORT_ID_OUTPUT_SET_RAMP 7
#define REPORT_ID_OUTPUT_EFFECT_OPERATION 8
#define REPORT_ID_OUTPUT_BLOCK_FREE 9
#define REPORT_ID_OUTPUT_DEVICE_CONTROL 10
#define REPORT_ID_OUTPUT_DEVICE_GAIN 11
#define REPORT_ID_FEATURE_CREATE_NEW_EFFECT 12
#define REPORT_ID_FEATURE_BLOCK_LOAD 13
#define REPORT_ID_FEATURE_POOL_REPORT 14
#endif
